apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
spec:
  domains:
    - peterchengg.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-website-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: my-website-ip
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
  labels:
    app: my-website
spec:
  defaultBackend:
    service:
      name: my-website-service
      port:
        number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-website-service
  namespace: default
spec:
  selector:
    name: my-website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30100
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      name: my-website
  replicas: 1
  template:
    metadata:
      labels:
        name: my-website
    spec:
      containers:
      - name: my-website
        image: asia-east2-docker.pkg.dev/geometric-shine-316204/docker/my_website:latest
        imagePullPolicy: Always       
        ports:
        - containerPort: 3000  
    
